server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_email
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: ${RABBITMQ_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
broker:
  queue:
    email:
      name: default.email
